Add a basic ui for bookings
AY2122S2-CS2103-F11-3/tp pull request #103
Opened 2022-03-23 16:00 UTC by hanhuiice

2022-03-24 06:04 UTC, flairekq requested changes
Overall looks good just some cosmetic issues to fix

2022-03-24 06:04 UTC, flairekq commented on src/main/java/seedu/trackbeau/ui/BookingListPanel.java
> +     * Custom {@code ListCell} that displays the graphics of a {@code Customer} using a {@code CustomerCard}.
Should be {@code Booking} using a {@code BookingCard}?

2022-03-24 06:04 UTC, flairekq commented on src/main/resources/view/BookingListCard.fxml
> +<HBox id="cardPane" fx:id="cardPane" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1">
i think need to change id="cardPane" to styleClass="cardPane" cause there's more than 1 element that is using id="cardPane".
`<HBox styleClass="cardPane" fx:id="cardPane" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1">
`

2022-03-24 12:26 UTC, isabelteo reviewed
LGTM

2022-03-24 12:26 UTC, isabelteo commented on src/main/java/seedu/trackbeau/ui/MainWindow.java
> +                    //bookingListPanel = new BookingListPanel(logic.getFilteredBookingList());
dead code

2022-03-25 06:27 UTC, flairekq reviewed
LGTM!

2022-03-25 06:27 UTC, flairekq approved these changes

2022-03-25 06:27 UTC, merged